version: '3.3'
services:
  oshopdb:
    image: mysql
    restart: always
    environment:
      # MYSQL_DATABASE: 'db'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password1'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password1'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - ./docker-entrypoint-initdb.d/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
      - ./dbdata:/var/lib/mysql

    command: 
      go run migrate.go

  oshopsrvr:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        HOME_DIR: $USER_HOME_DIR
        VERSION: 1
        CMD_NAME: $CMD_NAME
        PORT: $PORT
        CGO_ENABLED: $CGO_ENABLED
    depends_on:
      - oshoppdb
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'
# Names our volume
volumes:
  my-db: