version: '3.3'
services:
  oshopdb:
    volumes:
      # - ./docker-entrypoint-initdb.d/init-script.sql:/docker-entrypoint-initdb.d/init-script.sql
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      # - ./dbdata:/var/lib/mysql
    build: 
      context: .
      dockerfile: ./build/mysql/Dockerfile

    # image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'oshopdb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'dbadmin'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password1'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password1'
      MYSQL_PORT: 3306
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    

    # command: 
    #   go run migrate.go

  oshopsrvr:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # HOME_DIR: $USER_HOME_DIR
        VERSION: 1
        CMD_NAME: 'oshop'
        PORT: 8080
        CGO_ENABLED: '0'
    restart: always
    ports:
      - '8080:8080'
    expose:
      - '8080'
    depends_on:
      - oshopdb
# Names our volume
volumes:
  my-db: