CREATE DATABASE IF NOT EXISTS oshop;
CREATE USER 'dbadmin'@'%' IDENTIFIED BY 'password1';
GRANT CREATE, ALTER, INDEX, LOCK TABLES, REFERENCES, UPDATE, DELETE, DROP, SELECT, INSERT ON `oshop`.* TO 'dbadmin'@'%';
FLUSH PRIVILEGES;

SHOW DATABASES;